#!/usr/bin/env python3
"""Build the Symbolic Temporal Grounding web dashboard data.

The source artifacts are generated by the SORI-MLLM-Temporal-Grounding pilot:

  main/metadata/examples/pilot_extracted_triples.jsonl
  main/metadata/examples/pilot_extracted_note_tables.jsonl
  main/metadata/examples/pilot_rule_render_outputs.jsonl

This script converts them into a compact static JSON bundle for GitHub Pages and
copies the paired MIDI files into the page-local asset directory.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
from typing import Any


SITE_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SORI_ROOT = SITE_ROOT.parent / "SORI-MLLM-Temporal-Grounding"
PAGE_ROOT = SITE_ROOT / "exps" / "symbolic-tg"
DATA_OUTPUT = PAGE_ROOT / "assets" / "data" / "cases.json"
MIDI_OUTPUT_DIR = PAGE_ROOT / "assets" / "midi"

TASK_LABELS = {
    "pitch_key_consistency": "Pitch / Key",
    "timing_dynamics_control": "Timing / Dynamics",
    "melody_conditioned_texture": "Melody-Conditioned Texture",
}

TASK_ORDER = [
    "pitch_key_consistency",
    "timing_dynamics_control",
    "melody_conditioned_texture",
]


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_number}: invalid JSONL row") from exc
    return rows


def round_value(value: Any, digits: int = 3) -> Any:
    if isinstance(value, float):
        return round(value, digits)
    if isinstance(value, dict):
        return {key: round_value(child, digits) for key, child in value.items()}
    if isinstance(value, list):
        return [round_value(child, digits) for child in value]
    return value


def in_span(note: dict[str, Any], span: dict[str, Any]) -> bool:
    return note["start_tick"] >= span["start_tick"] and note["start_tick"] < span["end_tick"]


def note_match_signature(note: dict[str, Any]) -> tuple[str, int, int]:
    return (note.get("role", ""), note["start_tick"], note["end_tick"])


def note_sort_key(note: dict[str, Any]) -> tuple[float, int, float]:
    return (float(note.get("start_sec", 0)), int(note.get("pitch", 0)), float(note.get("end_sec", 0)))


def mark_visual_notes(source_notes: list[dict[str, Any]], target_notes: list[dict[str, Any]], row: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    span = row["temporal"]["spans"][0]
    changed_roles = set(row["diff_evidence"].get("changed_roles", []))
    task_family = row["subtask"]["family"]
    source_by_signature = {note_match_signature(note): note for note in source_notes}
    target_by_signature = {note_match_signature(note): note for note in target_notes}

    source_visual = []
    target_visual = []
    for note in source_notes:
        signature = note_match_signature(note)
        target_note = target_by_signature.get(signature)
        changed_exact = target_note is not None and target_note.get("pitch") != note.get("pitch")
        changed_role_span = note.get("role") in changed_roles and in_span(note, span)
        if task_family == "pitch_key_consistency":
            highlight = changed_exact
        else:
            highlight = changed_role_span
        source_visual.append({**note, "highlight": "changed_source" if highlight else "preserved"})

    for note in target_notes:
        signature = note_match_signature(note)
        source_note = source_by_signature.get(signature)
        changed_exact = source_note is not None and source_note.get("pitch") != note.get("pitch")
        changed_role_span = note.get("role") in changed_roles and in_span(note, span)
        if task_family == "pitch_key_consistency":
            highlight = changed_exact
        else:
            highlight = changed_role_span
        target_visual.append({**note, "highlight": "changed_target" if highlight else "preserved"})

    return source_visual, target_visual


def concise_evidence(row: dict[str, Any]) -> list[dict[str, str]]:
    values = row["evidence"]["values"]
    family = row["subtask"]["family"]
    items: list[dict[str, str]] = []
    local_key = values.get("local_key")
    if isinstance(local_key, dict) and local_key.get("status") == "supported":
        items.append({"label": "Local key", "value": str(local_key.get("value"))})
    melody = values.get("melody_sequence")
    if isinstance(melody, dict) and melody.get("status") == "supported":
        pitches = "--".join(melody.get("pitch_sequence", []))
        rhythm = melody.get("rhythm_pattern", "")
        contour = melody.get("pitch_contour", {}).get("value", "")
        if pitches:
            items.append({"label": "Melody sequence", "value": pitches})
        if rhythm:
            items.append({"label": "Rhythm pattern", "value": rhythm})
        if contour:
            items.append({"label": "Contour", "value": str(contour).replace("_", " ")})
    changed_note = values.get("changed_note_diff")
    if isinstance(changed_note, dict) and changed_note.get("status") == "supported":
        items.append({"label": "Changed note", "value": f"{changed_note.get('source_note')} → {changed_note.get('target_note')}"})
    timing = values.get("timing_grid")
    if isinstance(timing, dict) and timing.get("status") == "supported":
        items.append(
            {
                "label": "Onset deviation",
                "value": f"{timing.get('source_left_hand_onset_deviation_ms')} ms → {timing.get('target_left_hand_onset_deviation_ms')} ms",
            }
        )
    if family == "melody_conditioned_texture":
        source_count = values.get("source_accompaniment_notes", {}).get("value")
        target_count = values.get("target_accompaniment_notes", {}).get("value")
        ratio = values.get("density_ratio", {}).get("value")
        items.append({"label": "Accompaniment density", "value": f"{source_count} notes → {target_count} notes"})
        items.append({"label": "Density ratio", "value": str(ratio)})
    return items


def preprocess_steps(row: dict[str, Any], prompts: list[dict[str, Any]]) -> list[dict[str, Any]]:
    span = row["temporal"]["spans"][0]
    values = row["evidence"]["values"]
    rendered = {prompt["prompt_family"]: prompt["rendered_text"] for prompt in prompts}
    steps = [
        {
            "title": "1. Load Source / Target MIDI",
            "body": "Read the paired MIDI files and normalize notes into a common note table.",
            "fields": [
                {"label": "Source", "value": Path(row["source_midi"]).name},
                {"label": "Target", "value": Path(row["target_midi"]).name},
            ],
        },
        {
            "title": "2. Crop Edit Span",
            "body": "Apply half-open temporal grounding to crop the local edit region.",
            "fields": [
                {"label": "Seconds", "value": f"[{span['start_sec']}, {span['end_sec']})"},
                {"label": "Bar / beat", "value": f"{span.get('start_barbeat')} → {span.get('end_barbeat')}"},
            ],
        },
        {
            "title": "3. Extract Task Evidence",
            "body": "Compute only the symbolic features required by the selected subtask.",
            "fields": concise_evidence(row),
        },
        {
            "title": "4. Validate Diff And Controls",
            "body": "Use MIDI-diff evidence to decide which controls are supported and which claims must be omitted.",
            "fields": [
                {"label": "Changed roles", "value": ", ".join(row["diff_evidence"].get("changed_roles", []))},
                {"label": "Controls", "value": ", ".join(control["control_id"] for control in row.get("controls", []))},
                {"label": "Outside-change rate", "value": str(row["diff_evidence"].get("outside_change_rate"))},
            ],
        },
        {
            "title": "5. Render Prompt Families",
            "body": "Render caption/instruction variants from supported metadata and diff evidence.",
            "fields": [
                {"label": "base_M", "value": rendered.get("base_M", "—")},
                {"label": "base_D", "value": rendered.get("base_D", "—")},
                {"label": "base_MD", "value": rendered.get("base_MD", "—")},
            ],
        },
    ]
    if values.get("velocity_contour", {}).get("status") in {"unknown", "uncertain"}:
        steps[3]["fields"].append({"label": "Omitted", "value": f"velocity_contour:{values['velocity_contour']['status']}"})
    return steps


def build_cases(sori_root: Path) -> dict[str, Any]:
    examples = sori_root / "main" / "metadata" / "examples"
    triples = read_jsonl(examples / "pilot_extracted_triples.jsonl")
    note_tables = read_jsonl(examples / "pilot_extracted_note_tables.jsonl")
    render_outputs = read_jsonl(examples / "pilot_rule_render_outputs.jsonl")

    notes_by_case = {
        (row["triple_id"], row["kind"]): row for row in note_tables
    }
    prompts_by_case: dict[str, list[dict[str, Any]]] = {}
    for row in render_outputs:
        prompts_by_case.setdefault(row["triple_id"], []).append(
            {
                "prompt_family": row["prompt_family"],
                "mode": row["mode"],
                "training_stage": row["training_stage"],
                "rendered_text": row["rendered_text"],
                "used_controls": row.get("used_controls", ""),
                "omitted_features": row.get("omitted_features", ""),
            }
        )

    tasks = []
    cases = []
    for task_id in TASK_ORDER:
        task_rows = [row for row in triples if row["subtask"]["family"] == task_id]
        tasks.append(
            {
                "task_id": task_id,
                "label": TASK_LABELS[task_id],
                "case_count": len(task_rows),
                "description": task_description(task_id),
            }
        )

    for row in triples:
        triple_id = row["triple_id"]
        source_table = notes_by_case[(triple_id, "source")]
        target_table = notes_by_case[(triple_id, "target")]
        source_notes, target_notes = mark_visual_notes(source_table["notes"], target_table["notes"], row)

        copied_source = copy_midi_asset(sori_root, row["source_midi"])
        copied_target = copy_midi_asset(sori_root, row["target_midi"])
        prompts = sorted(prompts_by_case[triple_id], key=lambda item: ["base_M", "base_D", "base_MD"].index(item["prompt_family"]))

        cases.append(
            {
                "case_id": triple_id,
                "idx": len([case for case in cases if case["task_id"] == row["subtask"]["family"]]),
                "task_id": row["subtask"]["family"],
                "task_label": TASK_LABELS[row["subtask"]["family"]],
                "case_type": "editing",
                "title": case_title(row),
                "source_id": row["source_id"],
                "split": row["split"],
                "window": row["window"],
                "span": row["temporal"]["spans"][0],
                "subtask": row["subtask"],
                "edit_plan": row["edit_plan"],
                "diff_evidence": row["diff_evidence"],
                "validation": row["validation"],
                "controls": round_value(row.get("controls", [])),
                "evidence": round_value(row["evidence"]),
                "prompts": prompts,
                "preprocess_steps": preprocess_steps(row, prompts),
                "midi": {
                    "source": copied_source,
                    "target": copied_target,
                },
                "piano_roll": {
                    "original_label": "Original",
                    "predicted_label": "Predicted",
                    "source_notes": source_notes,
                    "target_notes": target_notes,
                    "ticks_per_beat": source_table["ticks_per_beat"],
                    "tempo_us_per_beat": source_table["tempo_us_per_beat"],
                },
            }
        )

    return {
        "schema_version": "symbolic_tg_dashboard_v0.1",
        "generated_from": str(sori_root),
        "title": "Fine-grained Temporal Grounding for Symbolic Music Generation and Editing",
        "tasks": tasks,
        "cases": cases,
    }


def task_description(task_id: str) -> str:
    descriptions = {
        "pitch_key_consistency": "Repair local pitch/key errors while preserving timing, rhythm, and non-target roles.",
        "timing_dynamics_control": "Adjust performance timing or dynamics using validated MIDI proxy metrics.",
        "melody_conditioned_texture": "Edit accompaniment texture while preserving the melody-conditioned scaffold.",
    }
    return descriptions[task_id]


def case_title(row: dict[str, Any]) -> str:
    family = row["subtask"]["family"]
    if family == "pitch_key_consistency":
        return "Off-key top-line repair with melody rhythm preservation"
    if family == "timing_dynamics_control":
        return "Left-hand onset de-jittering against the beat grid"
    if family == "melody_conditioned_texture":
        return "Accompaniment density reduction with fixed melody"
    return row["triple_id"]


def copy_midi_asset(sori_root: Path, midi_path: str) -> str:
    source = sori_root / midi_path
    MIDI_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    destination = MIDI_OUTPUT_DIR / source.name
    shutil.copy2(source, destination)
    return f"assets/midi/{destination.name}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sori-root", type=Path, default=DEFAULT_SORI_ROOT)
    parser.add_argument("--output", type=Path, default=DATA_OUTPUT)
    args = parser.parse_args()

    data = build_cases(args.sori_root.resolve())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote {len(data['cases'])} cases -> {args.output}")
    print(f"Copied MIDI assets -> {MIDI_OUTPUT_DIR}")


if __name__ == "__main__":
    main()
